name: Validate

on:
  workflow_call:

jobs:
	validate:
		runs-on: ubuntu-latest
		steps:
			- name: Setup Node
				uses: actions/setup-node@v2
				with:
					node-version: "17"
			- name: Install dependencies
				run: npm ci
			- name: Validate
				run: npm run validate
