name: Web deploy

on:
  push:
    branches:
      - main
    paths:
      - ./web/**

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

defaults:
  run:
    working-directory: ./web

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Install dependencies
        run: npm ci
      - name: Validate
        run: npm run validate

  heroku-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Heroku
        run: heroku container:login
      - name: Build and push app
        run: heroku container:push --app help380 web

  heroku-deploy-production:
    needs: [validate, heroku-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Heroku
        run: heroku container:login
      - name: Release web app
        run: heroku container:release --app help380 web
